# Generated by Django 2.0.4 on 2018-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palace', models.CharField(max_length=200)),
                ('time_at', models.IntegerField()),
                ('time_for_order', models.IntegerField()),
                ('cars', models.CharField(max_length=100)),
                ('car_quantity', models.IntegerField()),
                ('car_roominess', models.IntegerField()),
            ],
        ),
    ]
