# Generated by Django 2.0.4 on 2018-04-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='palace',
            new_name='place',
        ),
    ]
