# Generated by Django 2.0.4 on 2018-04-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180416_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='User',
            new_name='user',
        ),
    ]
