# Generated by Django 2.0.4 on 2018-04-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180418_1348'),
        ('orders', '0004_auto_20180418_1408'),
    ]

    operations = [
    ]
