# Generated by Django 2.0.4 on 2018-04-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20180418_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_for_order',
            field=models.DateField(),
        ),
    ]
