# Generated by Django 2.0.4 on 2018-04-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20180418_1526'),
        ('orders', '0006_auto_20180418_1537'),
    ]

    operations = [
    ]
