# Generated by Django 2.0.4 on 2018-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180418_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cars',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='place',
            field=models.CharField(max_length=200),
        ),
    ]
