# Generated by Django 2.0.4 on 2018-04-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_merge_20180420_1303'),
        ('orders', '0007_auto_20180420_1402'),
    ]

    operations = [
    ]
