# Generated by Django 2.0.4 on 2018-04-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20180425_1323'),
        ('orders', '0008_merge_20180425_1322'),
    ]

    operations = [
    ]
