# Generated by Django 2.0.4 on 2018-04-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20180425_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_for_order',
            field=models.DateTimeField(),
        ),
    ]
