# Generated by Django 2.0.4 on 2018-05-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('orders', '0013_orders_info_about_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cars',
        ),
        migrations.AddField(
            model_name='orders',
            name='cars',
            field=models.ManyToManyField(to='cars.Cars'),
        ),
    ]
