# Generated by Django 2.0.4 on 2018-04-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('sur_name', models.CharField(max_length=300)),
                ('middle_name', models.CharField(max_length=300)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users_number'),
        ),
    ]
