# Generated by Django 2.0.4 on 2018-04-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Users_number',
        ),
    ]
