# Generated by Django 2.0.4 on 2018-04-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
