# Generated by Django 2.0.4 on 2018-05-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100, unique=True)),
                ('year', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, upload_to='image')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
